sudo: required
services:
  - docker

before_install:
  - docker build -t spanaik/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spanaik/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us/-west-2-12345678"
  bucket_path: "docker-react" ## App Name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
